### ISSUE TITLE
Install without Sandstorm

### ISSUE THREAD

**Issue by k4r7u** [jacksingleton/hacker-slides#20]
Is there a way to install this awesome presentation app without the use of Sandstorm?
For example in a standard Webserver environment?

**Comment by jacksingleton** [comment]
Technically yes, with little modification you can deploy it to any server as it's really just a python script and some html/javascript.

The problem is that because this app was built for Sandstorm, it doesn't have any notion of users or document management. In fact - the app itself has no idea of multiple documents. It's written to handle just one set of slides.

What Sandstorm does is add user and document management, spinning up a new container (effectively an entire linux stack) for each document.

**Comment by k4r7u** [comment]
Thanks for the quick reply.
I think I will then use reveal.js in another way.
