### ISSUE TITLE
New Hacker Slides Graphics for Sandstorm.io Package

### ISSUE THREAD

**Issue by neynah** [jacksingleton/hacker-slides#28]
@jacksingleton 

I'm Nena Nguyen, designer at Sandstorm. I'm reaching out to you about Hacker Slide graphics because we're currently developing an app market and working on UI improvements to the existing Sandstorm shell design. See: https://groups.google.com/d/msg/sandstorm-dev/VRkPqX61cRs/Ts37SbqqKAAJ

As a part of this redesign, existing and new apps will need to submit 3 graphics (as a part of their SPK) for aesthetic and functional purposes.

I haven't been able to find any graphics for Hacker Slides, and was informed by @paulproteus that it's likely none exist so I went ahead and made some very simple (but I think appropriate) graphics for Hacker Slides.

If you think these are suitable, I can send you the appropriate files for when we need apps to update their SPKs(soonish). If not, I'll happily send over the illustrator/svg files for you to tweak or you can choose to come up with your own set.

Let me know~

:)

![hackerslides-preview1](https://cloud.githubusercontent.com/assets/855341/9238268/e7b33de0-4105-11e5-83af-90ee6f9917d4.png)

**Comment by neynah** [comment]
I attempted to create a pull request with these graphics but I'm on a Windows machine (which has a character limit of 260) so I was not able to clone to windows. Could you repackage under vagrant-spk?

**Comment by ocdtrekkie** [comment]
@neynah Does vagrant fix that? I'm assuming there's a filename somewhere in the package that is too big for Windows?

**Comment by neynah** [comment]
I believe @zarvox mentioned that it might resolve the issue but I'll double check.

**Comment by zarvox** [comment]
The issue appears to be that there's a bunch of npm dependencies, and the npm folks have decided to include every package's dependencies in a subfolder of that package called `node_modules`, recursively.  The longest path is `static/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/node_modules/request/node_modules/form-data/node_modules/combined-stream/node_modules/delayed-stream/test/integration/test-delayed-stream-auto-pause.js` which clocks in at a massive 247 characters.

(Actually @neynah if it's 247 characters, then it might succeed (barely) if you try to clone to a very short path like: `cd C:\src && git clone https://github.com/jacksingleton/hacker-slides hs` )

Git, like most software that runs on Windows, does not appear to use the [extended-length path option](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247%28v=vs.85%29.aspx#maxpath).  If it did, that would be one way to fix the issue.

If, rather than including the static dependencies outright, the package pulls them in via npm or bower in the guest, it's **possible** that the Virtualbox shared folder driver will use the "long paths" Windows API, whereas git on the host does not.  It's also possible that Virtualbox will also be constrained by the path limit, which means that contributors would need to attempt to clone the repo from the VM and do everything from within.

**Comment by neynah** [comment]
@zarvox Just tried it again in C: and still got:

error: unable to create file static/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phant
omjs/node_modules/request/node_modules/form-data/node_modules/combined-stream/node_modules/delayed-stream/test/integrati
on/test-delayed-stream-auto-pause.js (Filename too long)

**Comment by neynah** [comment]
I got it working. Thanks @zarvox. Will pull request now.

**Comment by jacksingleton** [comment]
Hey Nena! Sorry for the late response, I'm on vacation right now and get back the week if the 24th.

Thanks for taking the time to put the pull request together! (and for creating the graphics for that matter, looks awesome - clean and simple)

I may get to the pr this week, but if not count on the week of the 24th.

Jack

**Comment by ocdtrekkie** [comment]
Can be closed.
