### ISSUE TITLE
Allow disabling ACE

### ISSUE THREAD

**Issue by ndarilek** [jacksingleton/hacker-slides#35]
I'd like to use this as a convenient way of storing presentations in Sandstorm and delivering them without needing to set up a static server. Only, I'm a screen reader user and the editor is inaccessible (though apparently RevealJS is nicely accessible.)

Would it be possible to add a "Use visual editor" checkbox that is checked by default? If unchecked, we'd get a simple `<textarea/>` with the Markdown content. This might be beneficial for It's All Text users too; since ACE doesn't populate the text area, anyone wanting to pull the text into their own external editor would likely have a hard time doing so.

Thanks.

**Comment by jacksingleton** [comment]
Hey Nolan, yeah we can definitely do this.

I'm not sure how well the auto slide changing will work without Ace Editor, but it sounds like that won't matter much for your use case, correct?

**Comment by ndarilek** [comment]
How does this feature work? The editor makes it impossible for me to use 
it as is, so as long as there's a Reveal-based alternative for 
switching, I'm probably good.

Thanks.

**Comment by jacksingleton** [comment]
Hey Nolan, I haven't forgotten about this!

I sat down to work on Hacker Slides for the first time in quite a while and did some refactoring to make the codebase more approachable, and added some instructions and an introduction to the code to the README.

If you want to and have time, you should feel free to put together a PR! (and you could let me know what surprises you about the codebase so I can make it more clear and approachable)

Otherwise, this will be the next thing I work on (most likely sometime in the next two weeks)

**Comment by ndarilek** [comment]
A possibly easier and more universal fix would be switching entirely to [CKEditor](http://www.ckeditor.com). It is accessible out-of-the-box and now seems to have a Markdown addon. I certainly wouldn't mind having access to a nice editor component, and the CK developers did an amazing job. Ace, on the other hand, appears to have stalled out in its accessibility efforts.
